### ISSUE TITLE
Issues setting up still

### ISSUE THREAD

**Issue by draeician** [tonder0812/gogoanime#3]
Please don't close the issue until I can respond with at least it's functioning.   I just want to help if I can.

I recreated the venv with the 3.11:
python -V
Python 3.11.9

I added an anime to new.txt like in the README.md:
(venv) draeician@nomnom:~/git/gogoanime$ cat config/new.txt
ookami-to-koushinryou-merchant-meets-the-wise-wolf-dub

(venv) draeician@nomnom:/git/gogoanime$ python check.py
Traceback (most recent call last):
File "/home/draeician/git/gogoanime/check.py", line 12, in
from downloader import download_anime
File "/home/draeician/git/gogoanime/downloader.py", line 18, in
from printer import AbstractPrinter, FakePrinter
File "/home/draeician/git/gogoanime/printer/init.py", line 2, in
from .fake_printer import FakePrinter as _FakePrinter
File "/home/draeician/git/gogoanime/printer/fake_printer.py", line 1, in
from typing import override
ImportError: cannot import name 'override' from 'typing' (/usr/lib/python3.11/typing.py)
(venv) draeician@nomnom:~/git/gogoanime$

Getting a different error now.

I blew the venv again, installed python 3.12, redid the venv and NOW it executes without an error. Did I setup the new.txt correctly? What is a good workflow for this?

I tried this:
python main.py -id ookami-to-koushinryou-merchant-meets-the-wise-wolf-dub

I get this result:
Exception in thread Thread-1 (render):
Traceback (most recent call last):
File "/usr/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
self.run()
File "/usr/lib/python3.12/threading.py", line 1012, in run
self._target(*self._args, **self._kwargs)
File "/home/draeician/git/gogoanime/printer/printer.py", line 74, in render
self.__render()
File "/home/draeician/git/gogoanime/printer/printer.py", line 106, in __render
console.set_text(self.msg, int(self.scroller.position), should_set_cursor)
File "/home/draeician/git/gogoanime/printer/console/linux_console.py", line 1176, in set_text
print(msg, end="", flush=True)
BlockingIOError: [Errno 11] write could not complete without blocking

I tried with -Iwhitelist, but got this:
python main.py -id ookami-to-koushinryou-merchant-meets-the-wise-wolf-dub -Iwhitelist
whitelist ep ids: (leave blank to stop inputing)

And the program exists.

**Comment by tonder0812** [comment]
Sorry for closing the previous issue (it was my first time answering one) and thanks for pointing out the override error, I am updating the required python version to be 3.12

Regarding the new issue it seems to be an error with printing large amounts of text caused by an error in the download part that was always failing on linux leading to an infinite retry loop, should be fixed in the latest commit

**Comment by tonder0812** [comment]
@draeician can I assume this solved your problems?

**Comment by draeician** [comment]
On a cruise but will check when i get back.

**Comment by draeician** [comment]
Have you tried downloading with this yet?  They have made some pretty intense changes to the site.  Even the direct download links themselves aren't letting videos download now.
Example:
https://gogoanime3.co/nozomanu-fushi-no-boukensha-dub-episode-9

Even logged in, you get "no sponsor" message.

**Comment by tonder0812** [comment]
Should work on the latest commit (that fixes the url)

**Comment by draeician** [comment]
It's working now, create project so far.  I'll do a pull request with some documentation changes I think would make it easier to read and understand for some.  It took me reading it a few times to get it right and understand.  Might just be for me, but you can take or leave the updates.
